Add the Notifications and Footer components to Storybook
BuildWithSpruce/mappedin-homescreen pull request #7
Opened 2023-07-05 14:43 UTC by Aa-thomas

2023-07-06 12:40 UTC, mitchellbutler requested changes
Hey, these are looking good. I've added a bunch of comments for your review.

For custom styling with Shallot, I think it would be helpful for you to take a look at how I've switched a bunch of the other components to a more traditional `styled-components` approach while still using all of the mixins.

For example, you can check out the Search card:
* [In the `index.tsx`](https://github.com/BuildWithSpruce/mappedin-homescreen/blob/main/src/components/SearchCard/index.tsx) we construct the component and we use a lot of the Shallot `style-props` but we don't use the shallot prop much or do a lot of conditional styling.
* Then [there's a new styles.ts file](https://github.com/BuildWithSpruce/mappedin-homescreen/blob/main/src/components/SearchCard/style.ts), which contains a lot of the more custom styling for these components.

If you haven't already, it's probably worth reviewing the [`styled-components`](https://styled-components.com/) docs. I thnk they'd be really helpful for understanding this pattern.

2023-07-06 12:40 UTC, mitchellbutler commented on src/app/page.tsx
> +            gridArea="."
Heads up that this will result in a CSS value of `grid-area: •;` which technically shouldn't do anything. My understanding is that the `•` denotes an empty space in the `grid-template-areas`, which should be filled in with anything that doesn't have a `grid-area` specified.

2023-07-06 12:40 UTC, mitchellbutler commented on src/components/Footer/index.tsx
> +  fontSize: number
I think we should stick with Shallot's `fontSize` specifications here for consistency with other fonts on the interface and so that it reflects changes in the theme.

2023-07-06 12:40 UTC, mitchellbutler commented on src/components/Footer/index.tsx
> +  buttonSize: number
As with my comment above, I don't think we need to expose this through props.

When we do have to expose values like this, I think we should stick with Shallot's use of `...Units` approach here for consistent sizing and so that it reflects changes in the theme (e.g., `avatarSizeUnits` or `buttonSizeUnits`).

2023-07-06 12:40 UTC, mitchellbutler commented on src/components/Footer/index.tsx
> +  artistDisplayPhoto: StaticImageData | string
When we have a lot of keys prefixed like this, I think it's a good opportunity that we could combine these into one object. **For example:**
```
type WallpaperArtist {
  name: string
  credits: string
  link: string
  avatar: StaticImageData | string
}
```

2023-07-06 12:40 UTC, mitchellbutler commented on src/components/Footer/index.tsx
> +            Wallpaper: {artistCredits}
This feels like more of a property of the wallpaper than the artist, actually. Maybe we should be passing in a wallpaper object like this:
```ts
type Wallpaper {
  name: string
  image: StaticImageData | string
  year: number
  artist: {
    name: string
    link: string
    avatar: StaticImageData | string
  }
}
```

In which case, this value could be: `{wallpaper.name} by {wallpaper.artist.name} ({wallpaper.year})`

2023-07-06 12:40 UTC, mitchellbutler commented on src/components/Footer/index.tsx
> +                fontSize: `${fontSize - 2}px`,
See my comments earlier on font sizes. I think we should switch to using a theme value here.

2023-07-06 12:40 UTC, mitchellbutler commented on src/components/NotificationsCard/Pagination/index.tsx
> +      {' '}
I think this is extraneous.

2023-07-06 12:40 UTC, mitchellbutler commented on src/components/NotificationsCard/Pagination/index.tsx
> +      <Column alignCenter alignMiddle shallot={{ gap: '3px' }}>
For values like `gap: '3px'` - I think we need to base these on grid units (e.g., `${getUnits(1/4)}px`).

2023-07-06 12:40 UTC, mitchellbutler commented on src/components/NotificationsCard/Pagination/index.tsx
> +            background: `conic-gradient(white 0% ${fillPercentage}%, transparent ${fillPercentage}% 100%)`,
👍 Neat!

2023-07-07 15:28 UTC, Aa-thomas commented on src/components/Footer/index.tsx
> +            Wallpaper: {artistCredits}
done!

2023-07-07 15:35 UTC, Aa-thomas commented on src/components/Footer/index.tsx
> +  artistDisplayPhoto: StaticImageData | string
done!

2023-07-07 15:52 UTC, Aa-thomas commented on src/components/Footer/index.tsx
> +  fontSize: number
done!

2023-07-07 15:53 UTC, Aa-thomas commented on src/components/Footer/index.tsx
> +                fontSize: `${fontSize - 2}px`,
done!

2023-07-07 16:07 UTC, Aa-thomas commented on src/components/NotificationsCard/Pagination/index.tsx
> +            background: `conic-gradient(white 0% ${fillPercentage}%, transparent ${fillPercentage}% 100%)`,
Thanks ! 😎

2023-07-07 19:43 UTC, Aa-thomas commented on src/components/NotificationsCard/Pagination/index.tsx
> +      <Column alignCenter alignMiddle shallot={{ gap: '3px' }}>
done!

2023-07-07 19:43 UTC, Aa-thomas commented on src/components/Footer/index.tsx
> +  buttonSize: number
done!

2023-07-10 15:01 UTC, merged